### PR TITLE
feat: "lite" build tags to match go-ssb

### PR DESCRIPTION
**Pull request by decentral1se**
@staltz 

Chasing a fix for https://github.com/ssbc/go-ssb/issues/183#issuecomment-1297455458.

Related to https://github.com/ssbc/margaret/pull/25.

### CODE REVIEW

**Comment by staltz** [comment]
@decentral1se What do you think if sometimes you ask @mycognosist for a review? And @mycognosist do you mind reviewing some go-ssb PRs? I've been reviewing decentral1se's great PRs, but I don't use go-ssb that much, apart from go-ssb-room. You use go-ssb a bit more than me, and it seems you two already have some good interaction going on.

@mycognosist has access to merge PRs in ssbc, so we shouldn't have any problems. Also, feel free to still ask me for reviews, I don't mind. :)

**Comment by mycognosist** [comment]
I can do that with pleasure, @staltz . Sorry, I should have suggested that sooner. Thanks for your reviews and actions in go-land :)

**Review by mycognosist — APPROVED** [review]
Going to do my best to read and comprehend all the changes in these Go PR's :)

This one looks good to me 🟢

**Comment by decentral1se** [comment]
Thanks for your work @staltz! Thanks for stepping in @mycognosist!

Also, can someone add me to ssbc? The automation is broken / the Go repos are not included but I guess I would have access by now? https://github.com/ssbc/.github/issues/4 https://github.com/ssbc/.github/issues/3 I could imagine merging some of the smaller PRs myself on the way to more review-able changes... might be less work for y'all! I'd still open PRs for visibility but not everything needs to wait while we're in this testing phase imho...

**Comment by mycognosist** [comment]
@decentral1se 

As mentioned in https://github.com/ssbc/.github/issues/3#issuecomment-1298448749, I think you will soon be recommended by the CI. Some details about membership here: https://github.com/ssbc/.github/blob/master/MEMBERSHIP.md

Until then, I'm happy to merge PR's for you and will give a heads-up if I'm going to be AFK for a few days. Feel free to ping me when needed! Thanks for the patience, I know it can be a little tedious waiting for others to merge.

**Pull request merged**
